# Generated by Django 5.0.2 on 2024-03-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=100)),
                ('pro_price', models.PositiveIntegerField()),
                ('pro_brand', models.CharField(max_length=100)),
            ],
        ),
    ]
